import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:todo_app/configs/strings.dart';
import 'package:todo_app/models/archive.dart';
import 'package:todo_app/models/board.dart';

class Firestore {
  static Future<List> getAllBoards(String collection) async {
    return (await FirebaseFirestore.instance.collection(collection).get())
        .docs
        .map((item) => BoardData.fromJson(item.data()))
        .toList();
  }

  static Future<List> getAllArchives() async {
    return (await FirebaseFirestore.instance.collection(ARCHIVE_COLLETION).get())
        .docs
        .map((item) => Archive.fromJson(item.data()))
        .toList();
  }

  static Future addEntryWithAutogeneratedId(
      String collection, Map<String, dynamic> data) async {
    await FirebaseFirestore.instance.collection(collection).add(data);
  }

  static Future updateOrCreate(
      String documentId, Map<String, dynamic> data) async {
    var result = await FirebaseFirestore.instance
        .collection(BOARD_COLLECTION)
        .where("uuid", isEqualTo: documentId)
        .get();

    if (result.docs.isEmpty) {
      await addEntryWithAutogeneratedId(BOARD_COLLECTION, data);
    } else {
      var id = result.docs.first.id;

      await FirebaseFirestore.instance
          .collection(BOARD_COLLECTION)
          .doc(id)
          .update(data);
    }
  }

}
